// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2TjBQndxwp5wBLyo_Y9RLraQkCLs4HqQ',
    appId: '1:228151860752:web:1c76f396dddf8f5915f495',
    messagingSenderId: '228151860752',
    projectId: 'agriamuse-82ae5',
    authDomain: 'agriamuse-82ae5.firebaseapp.com',
    storageBucket: 'agriamuse-82ae5.appspot.com',
    measurementId: 'G-98FHBK6HBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWYEkLveZen9uPt_5LHO44CVBjT_OcAY4',
    appId: '1:228151860752:android:2087767d1c25fe5815f495',
    messagingSenderId: '228151860752',
    projectId: 'agriamuse-82ae5',
    storageBucket: 'agriamuse-82ae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL-IjJDy1aE1SU_d1jI6bwFzhZJClZR8E',
    appId: '1:228151860752:ios:baf3a382487326b315f495',
    messagingSenderId: '228151860752',
    projectId: 'agriamuse-82ae5',
    storageBucket: 'agriamuse-82ae5.appspot.com',
    iosBundleId: 'com.example.agriamuse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL-IjJDy1aE1SU_d1jI6bwFzhZJClZR8E',
    appId: '1:228151860752:ios:466713f004ed991515f495',
    messagingSenderId: '228151860752',
    projectId: 'agriamuse-82ae5',
    storageBucket: 'agriamuse-82ae5.appspot.com',
    iosBundleId: 'com.example.agriamuse.RunnerTests',
  );
}
